
stages:
  - build

pages:
  image: ruby:2.7
  stage: build
  script:
    - gem install bundler
    - bundle install
    - bundle exec jekyll build -d public
  tags:
    - docker
  artifacts:
    paths:
      - public

wheel:
  image: python:3-alpine
  stage: build
  tags:
    - docker
  script: python setup.py bdist_wheel
  artifacts:
    paths:
    - dist
